[package]
name = "double_dyn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
double-dyn-macros = {path = "./double-dyn-macros"}

